### ISSUE TITLE
Error while trying to use pedigree file (-S)

### ISSUE THREAD

**Issue by barslmn** [samtools/bcftools#1696]
Hi,
I am having following issue while trying to variant call with trio constraint. However I am getting the following error while trying to supply a ped file. I had no problems while calling variants without the trio constraint (without -S and -C). I am guessing even though documentation says that first column is ignored bcftools reads it as a sample name?

Here is the command i am trying to run and the error it gives:
```
$ bcftools mpileup --threads 12 -a "FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SP,FORMAT/SCR,INFO/AD,INFO/ADF,INFO/ADR,INFO/SCR,FORMAT/ADR,FORMAT/ADF" -Ou -f /media/bar/2tb/dbs/humandb/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz -R GRCh37_exome.bed.gz UG_i_S4.bam UG_a_S5.bam UG_b_S6.bam | bcftools call --threads 12 -s  -C trio -S UG.ped -mv -Ob -o UG_trio_calls.bcf
 
Warning: No such sample in the VCF: UG
Detected 0 samples in 0 trio families
No such sample: UG
```

Here is the ped file:

```
UG	UG_i_S4	UG_b_S6	UG_a_S5	1
```

Thanks

**Comment by pd3** [comment]
What are the names of the samples in the VCF produced by `mpileup`? The samples names in that VCF output must be present in the PED file. 

The program determines the sample names from `@RG` lines in the BAM header. If the samples need to be renamed, the `mpileup --read-groups` option may come in handy.

To view the sample names assigned by default, try
```
bcftools mpileup ... | bcftools query -l
```

**Comment by barslmn** [comment]
Read groups are set to sample names in the alignment step so the following command gives the expected output:

```
❯ bcftools mpileup --threads 12 -a FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SP,FORMAT/SCR,INFO/AD,INFO/ADF,INFO/ADR,INFO/SCR,FORMAT/ADR,FORMAT/ADF,FORMAT/QS -Ou -f ../Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz -R GRCh37_exome.bed.gz UG_i_S4.bam UG_a_S5.bam UG_b_S6.bam | bcftools query -l
[mpileup] 3 samples in 3 input files
[mpileup] maximum number of reads per input file set to -d 250
UG_i_S4
UG_a_S5
UG_b_S6
```

Also while using the same pedigree file with the trio-dnm2 plugin there were no problems.

**Comment by pd3** [comment]
Looking at the command again, there seems to be a typo:
```
[...] -s  -C trio -S UG.ped [...]
```
Only one of `-s` or `-S` should be given and they should be followed by a parameter.

I believe this finding should resolve the problem.

**Comment by barslmn** [comment]
Oh, that -s must be an artifact from testing different argument combinations.  The problem persists with just `-S`.

![image](https://user-images.githubusercontent.com/43095157/162269715-bc26ef57-26d2-42eb-8b45-0d500583013d.png)

Command and stderr as text:
```
 bcftools mpileup --threads 12 -a FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SP,FORMAT/SCR,INFO/AD,INFO/ADF,INFO/ADR,INFO/SCR,FORMAT/ADR,FORMAT/ADF,FORMAT/QS -Ou -f ../Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz -R GRCh37_exome.bed.gz UG_i_S4.bam UG_a_S5.bam UG_b_S6.bam | bcftools call --threads 12 --ploidy-file ploidy -C trio -S UG.ped -mv -Ob -o UG_calls.bcf
[mpileup] 3 samples in 3 input files
[mpileup] maximum number of reads per input file set to -d 250
Warning: No such sample in the VCF: UG
Detected 0 samples in 0 trio families
No such sample: UG
```

With just `-s`, it gives an error which is to be expected.
![image](https://user-images.githubusercontent.com/43095157/162270728-60b307e1-7889-45a3-b26b-22954f7f2d34.png)

**Comment by pd3** [comment]
What version of bcftools are you running? If it's the latest, can you create a small test case to reproduce the problem? I think the header from mpileup output and the ped file should suffice.

**Comment by barslmn** [comment]
Here are the header from the mpileup output and the ped file.

[mpileup_header.txt](https://github.com/samtools/bcftools/files/8456307/mpileup_header.txt)
[UG.ped.txt](https://github.com/samtools/bcftools/files/8456308/UG.ped.txt)

**Comment by pd3** [comment]
This was indeed a bug. It is now fixed, thank you for the test case.

**Comment by barslmn** [comment]
Thanks a lot, I got the last build and error seems to be fixed.
