### ISSUE TITLE
merge issues with monoallelic positions

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#412]
I'm not quite sure how to deal with the following scenario.

I'm merging lots of vcf's. Some vcf's have the REF homozygotes called with no ALT specified. When merging using `-m none`, positions with no ALT don't seem to get merged properly. i.e. each observed genotype at the same position ends up on it's own line.

How might I avoid this so that the merging creates one line per position. I guess this requires two pieces of logic. First that the mono-allelics get merged and second that mono-allelics can be merged with bi-allelics.

If this can't be done via merging is there a way to resolve and collapse the variants using `norm`. Conventional multi-allelics should be split across multiple lines.

example output:
https://gist.github.com/655c3c579098aa41881c15c68a5aa5cd

**Comment by dwaggott** [comment]
Running `bcftools norm -m +` on the above file seems to just remove the mono-allelic positions. The genotypes 0/0 from these positions are not present in the output.

**Comment by pd3** [comment]
Indeed, this is a bug. There is a new version of `bcftools merge` which should handle this properly, please check here http://pd3.github.io/bcftools (the commit df7f451 is required for this to work). Thank you for the bug report.

**Comment by dwaggott** [comment]
Thanks! Are the fixes in the experimental fork being merged back here?

**Comment by dwaggott** [comment]
Output looks wonky. Each GT at the same position is now on it's own line.

https://gist.github.com/cf8c16830b71efea264d577eaf0e03ee

**Comment by pd3** [comment]
Apologies, the bug did not show up in my tests. This commit should fix it https://github.com/pd3/bcftools/commit/9746e17b85c79bec5dfb50e0abb85f6336f661ee

RE your question about merging the fixes back into the main repository: The `merge` command in the experimental fork has been significantly reworked about a year ago and since then we've been waiting for other work to happen before it can be merged back. There is a long overdue bugfix release under way, the merge is planned after that. Unfortunately, I cannot give any time estimate when this finally happens.

**Comment by dwaggott** [comment]
Ah, thanks. I'll use the experimental for merging.

I'm still getting multiple lines for the same position.
https://gist.github.com/e7c37b9bd3326db387413ff36391c78d

**Comment by pd3** [comment]
The output you showed was produced by the previous commit df7f451, not the fixed one 9746e17
