### ISSUE TITLE
segfault when mixing -x and -c in annotate

### ISSUE THREAD

**Issue by abjonnes** [samtools/bcftools#428]
I got a segfault when trying something like this:

    bcftools annotate -a myannotations.vcf.gz -x INFO -c INFO/TAG -o results.vcf.gz -O z input.vcf.gz

I was trying to first remove all INFOs from the input, then add the TAG annotation from the annotation file. I guess this isn't possible at this point but the program should probably tell you about it instead of segfaulting (and the documentation could probably be a little clearer on this point).

**Comment by pd3** [comment]
Have you got a test case? I was not able to reproduce this with the most recent version. For example using the files from bcftools/tests:

     bcftools annotate -x INFO -c INFO/IINT -a annots2.vcf.gz annotate2.vcf.gz

**Comment by mcshane** [comment]
```
bcftools annotate -x INFO -a tmp/annotate.tab.gz -h test/annotate.hdr -c CHROM,POS,REF,ALT,ID,QUAL,INFO/T_INT,INFO/T_FLOAT,INDEL tmp/annotate.vcf.gz
```
which is just adding `-x INFO` to the first annotate test

**Comment by abjonnes** [comment]
Interestingly, the problem appears for that test case if you include only one value for **some combinations** of  `IINT` annotations in `annots2.vcf`. Here, I've deleted all but one `IINT` value from every record in `annots2.vcf` (with nonmissing `IINT` values), and `annotate2.vcf` is unchanged:

```
$ zcat gh-annots2.vcf.gz
##fileformat=VCFv4.1
##FILTER=<ID=q99,Description="Quality below 10">
##contig=<ID=1,assembly=b37,length=249250621>
##reference=file:///lustre/scratch105/projects/g1k/ref/main_project/human_g1k_v37.fasta
##INFO=<ID=FLAG,Number=0,Type=Flag,Description="Test type">
##INFO=<ID=IINT,Number=.,Type=Integer,Description="Test type">
##INFO=<ID=IFLT,Number=.,Type=Float,Description="Test type">
##INFO=<ID=ISTR,Number=.,Type=String,Description="Test type">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=FINT,Number=.,Type=Integer,Description="Test type">
##FORMAT=<ID=FFLT,Number=.,Type=Float,Description="Test type">
##FORMAT=<ID=FSTR,Number=.,Type=String,Description="Test type">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  B       A
1       3000001 .       C       T       .       .       .       GT      .       .
1       3000002 id      C       T       99      q99     FLAG;IINT=88;IFLT=8.8,9.9;ISTR=888,999  GT:FINT:FFLT:FSTR       1|1:88,99:8.8,9.9:888,999       0|1:77:7.7:77
1       3000003 id      C       T       99      q99     FLAG;IINT=99;IFLT=8.8,9.9;ISTR=888,999  GT:FINT:FFLT:FSTR       1|1:88,99:8.8,9.9:888,999       0|1:77:7.7:77
1       3000004 id      C       T       99      q99     FLAG;IINT=88;IFLT=8.8,9.9;ISTR=888,999  GT:FINT:FFLT:FSTR       1|1:88,99:8.8,9.9:888,999       0|1:77:7.7:77
$ zcat gh-annotate2.vcf.gz
##fileformat=VCFv4.1
##contig=<ID=1,assembly=b37,length=249250621>
##reference=file:///lustre/scratch105/projects/g1k/ref/main_project/human_g1k_v37.fasta
##INFO=<ID=FLAG,Number=0,Type=Flag,Description="Test type">
##INFO=<ID=IINT,Number=1,Type=Integer,Description="Test type">
##INFO=<ID=IFLT,Number=1,Type=Float,Description="Test type">
##INFO=<ID=ISTR,Number=1,Type=String,Description="Test type">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=FINT,Number=1,Type=Integer,Description="Test type">
##FORMAT=<ID=FFLT,Number=1,Type=Float,Description="Test type">
##FORMAT=<ID=FSTR,Number=1,Type=String,Description="Test type">
##FILTER=<ID=q11,Description="Quality below 10">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  A       B       C
1       3000001 xx      C       T       11      PASS    FLAG;IINT=11;IFLT=1.1;ISTR=xxx  GT:FINT:FFLT:FSTR       0/0:11:1.1:xxx  0/0:11:1.1:x    0/0:11:1.1:x
1       3000002 .       C       T       .       .       .       GT      .       .       .
1       3000003 xx      C       T       11      q11     FLAG;IINT=.;IFLT=.;ISTR=.       GT:FINT:FFLT:FSTR       0/0:.:.:.       0/0:.:.:.       0/0:.:.:.
1       3000004 xx      C       T       11      q11     FLAG;IINT=11;IFLT=1.1;ISTR=xxx  GT:FINT:FFLT:FSTR       0/0:11:1.1:x    0/0:11:1.1:xxx  0/0:11:1.1:xxx
$ bcftools annotate -a gh-annots2.vcf.gz -x INFO -c INFO/IINT gh-annotate2.vcf.gz
Segmentation fault (core dumped)
```

Further, if I alter the original `annots2.vcf` to have only one value for `IINT` for the **second** record only (pos `3000002`), there is no segfault; if I do so for the **third** record only (pos `3000003`), there is a segfault. Additionally, in cases without a segfault, the output does not have an `IINT` entry in the header (there are no `INFO` headers at all).

**Comment by pd3** [comment]
Hi, this should be fixed now. Thanks for reporting the bug

**Comment by abjonnes** [comment]
Hi, I still get segfaults and the header issue doesn't appear to be fixed either. I built against samtools/bcftools@47e4f4c3c1629450709063808dccd7a4ed7dc1fd and samtools/htslib@4295de423b015b216587a9043f1c0504d5d48f3f.

**Comment by pd3** [comment]
Hi, can you please check if this solves the problem? It works on my testing data, but there may be more situations not covered by this fix. Thanks

**Comment by abjonnes** [comment]
Hi, this seems to have resolved the segfaults! (samtools/bcftools@e6fb7f2b783558e6476e7fdb1c78d4e262d07d68 and samtools/htslib@4295de423b015b216587a9043f1c0504d5d48f3f.) The output for the example files I supplied above still doesn't have an `INFO` header for `IINT`, though (no `INFO` headers at all).

Thanks!

**Comment by pd3** [comment]
This commit 00b824a should fixe the header issue.

**Comment by abjonnes** [comment]
Seems to work! Great, thanks for your help.

**Comment by pd3** [comment]
Cool, thanks for testing!
