### ISSUE TITLE
bcftools call -C alleles -T input requirements

### ISSUE THREAD

**Issue by fpbarthel** [samtools/bcftools#915]
I would like to suggest an enhancement to `bcftools call -C alleles`. The `targets.tsv.gz` file that can be supplied using `-T` is not very intuitive. Would it be possible to allow one to supply a VCF file?

I've also noticed that when one supplies multi-allelic variants in the `targets.tsv.gz` split across multiple lines, eg.
```
6       87072849        G,A
6       87072849        G,C
```
It will ignore the second line without warning and only perform a call for the first.

**Comment by fpbarthel** [comment]
Also, I am getting various `fixme?` warning messages running bcftools:

```
$ bcftools mpileup -a DP,AD,SP,ADF,ADR -R targets.bed -f human_g1k_v37_decoy.fasta CEUTrio.HiSeq.WGS.jaffe.b37_decoy.NA12878.chr6.clean.dedup.recal.20120117.bambcftools call -C alleles -T targets.tsv.gz -m -A - > test.vcf

Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
[W::hts_idx_load2] The index file is older than the data file: CEUTrio.HiSeq.WGS.jaffe.b37_decoy.NA12878.chr6.clean.dedup.recal.20120117.bam.bai
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250

fixme? Cannot constrain to A
fixme? Cannot constrain to T
fixme? Cannot constrain to GT
fixme? Cannot constrain to G
fixme? Cannot constrain to CA
fixme? Cannot constrain to G
fixme? Cannot constrain to C
fixme? Cannot constrain to A
fixme? Cannot constrain to A
fixme? Cannot constrain to GT
fixme? Cannot constrain to GTGTGTC
fixme? Cannot constrain to CACACACA
fixme? Cannot constrain to GT
```

Not clear what these indicate

**Comment by pd3** [comment]
Looking in the code, I think this will be a problem with handling the symbolic "unseen" star allele. I just pushed a commit which should print a more informative error message. Please try it out and let me know.

**Comment by fpbarthel** [comment]
I accidentally deleted the test case that I had to reproduce this so it took me a while to get back to this. Here is the output (using a different, smaller example than before). It still shows the errors, but the error messages are more helpful now:

```
$bcftools mpileup -a DP,AD,SP,ADF,ADR -R targets.bed -f human_g1k_v37_decoy.fasta CEUTrio.HiSeq.WGS.jaffe.b37_decoy.NA12878.chr6.clean.dedup.recal.20120117.bam | bcftools call -C alleles -T targets.tsv.gz -m -A - > test.vcf
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
[W::hts_idx_load2] The index file is older than the data file: CEUTrio.HiSeq.WGS.jaffe.b37_decoy.NA12878.chr6.clean.dedup.recal.20120117.bam.bai
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
Fixme? Cannot constrain to 1-th allele (T). VCF=TAAAAAAAAA,TAAAAAAAAAA  TAB=TA,T
Fixme? Cannot constrain to 1-th allele (T). VCF=CGGGGG,CGGGGGGG TAB=C,T
Fixme? Cannot constrain to 1-th allele (GT). VCF=GTTTTTTT,GTTTTTT       TAB=G,GT
```

There are hundreds of `C,T`s in my targets.tsv.gz file but the other two are easier to trace. Here is my targets.tsv file after reducing it to  `TA,T` and `G,GT` only:

```
6       263722  TA,T
6       321731  TA,T
6       455568  G,GT
```

And this is the resulting vcf:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878
6       263722  .       TA      T       282     .       DP=244;SGB=-0.379885;RPB=1;MQB=1;MQSB=0.992792;BQB=1;MQ0F=0;AC=0;AN=2;DP4=83,29,0,1;MQ=58       GT:PL:DP:SP:ADF:ADR:AD  0/0:0,255,255:113:0:83,0:29,0:112,0
6       321731  .       TA      T       282     .       DP=230;VDB=0.873285;SGB=-0.511536;RPB=0.586388;MQB=0.995059;MQSB=0.961422;BQB=0.0173028;MQ0F=0;AC=0;AN=2;DP4=148,61,1,2;MQ=58GT:PL:DP:SP:ADF:ADR:AD   0/0:0,255,255:212:7:148,0:61,0:209,0
6       455568  .       G       GT      282     .       DP=106;MQSB=0.81117;MQ0F=0;AC=0;AN=2;DP4=61,32,0,0;MQ=58        GT:PL:DP:SP:ADF:ADR:AD  0/0:0,255,255:93:0:61,0:32,0:93,0
```

**Comment by pd3** [comment]
Hi, sorry for the delay. This is just to record the latest state of things.

In the meantime there was an update of vcfcall.c (b558e646) which makes the messages disappear. Unfortunately, it does not really solve the issue. The problem is that it only handles duplicate lines in the TSV file but does not address the duplicate SNP vs indel lines in the VCF. Consequently, indel TSV lines are incorrectly matched to SNP lines in the VCF, because the SNP lines come first from mpileup. In order to fix this, we'd need a double buffering: for duplicate VCF lines and for duplicate TSV lines, not just for the TSV lines (which is done now). Ideally this would be an improvement (or rather a complete rewrite) of bcf_synced_reader in htslib. However, that it's even more complex, as the reader works with arbitrary number of input files where alleles and duplicate lines can appear in any combination.

**Comment by pd3** [comment]
This should be now fixed by c76dbcf. Please let me know if not.

**Comment by fpbarthel** [comment]
Thanks for addressing this! I'll see when I have time to test if this works for me now.
